apiVersion: v1
kind: Service
metadata:
  name: wordpresssvc
  namespace: development
  labels:
    app: wordpresssvc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: wordpress
    ---
    apiVersion: v1
kind: Service
metadata:
  name: mysqlsvc
  namespace: development
  labels:
    app: mysqlsvc
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql
